import Config

# config/runtime.exs is executed for all environments, including
# during releases. It is executed after compilation and before the
# system starts, so it is typically used to load production configuration
# and secrets from environment variables or elsewhere. Do not define
# any compile-time configuration in here, as it won't be applied.
# The block below contains prod specific runtime configuration.

# ## Using releases
#
# If you use `mix release`, you need to explicitly enable the server
# by passing the PHX_SERVER=true when you start it:
#
#     PHX_SERVER=true bin/harness start
#
# Alternatively, you can use `mix phx.gen.release` to generate a `bin/server`
# script that automatically sets the env var above.
if System.get_env("PHX_SERVER") do
  config :harness, HarnessWeb.Endpoint, server: true
end

config :harness, HarnessWeb.Endpoint,
  http: [port: String.to_integer(System.get_env("PORT", "4000"))]

if config_env() == :prod do
  harness_home = Path.expand("~/.harness")
  File.mkdir_p!(harness_home)

  database_path = System.get_env("DATABASE_PATH") || Path.join(harness_home, "harness.db")

  config :harness, Harness.Repo,
    database: database_path,
    pool_size: String.to_integer(System.get_env("POOL_SIZE") || "5")

  # Single-user daemon: the secret lives in ~/.harness (generated by
  # `mix harness.install`), never in the repo or the plist.
  secret_key_base =
    System.get_env("SECRET_KEY_BASE") ||
      (
        secret_path = Path.join(harness_home, "secret_key_base")

        case File.read(secret_path) do
          {:ok, secret} ->
            String.trim(secret)

          {:error, _} ->
            raise """
            No SECRET_KEY_BASE env var and no #{secret_path} file.
            Run `mix harness.install` (or `mix phx.gen.secret > #{secret_path}`).
            """
        end
      )

  config :harness, :dns_cluster_query, System.get_env("DNS_CLUSTER_QUERY")

  # Loopback only — phone access goes through `tailscale serve`, never LAN.
  config :harness, HarnessWeb.Endpoint,
    url: [host: "localhost", port: 4040],
    http: [
      ip: {127, 0, 0, 1},
      port: String.to_integer(System.get_env("PORT") || "4040")
    ],
    secret_key_base: secret_key_base

  # ## SSL Support
  #
  # To get SSL working, you will need to add the `https` key
  # to your endpoint configuration:
  #
  #     config :harness, HarnessWeb.Endpoint,
  #       https: [
  #         ...,
  #         port: 443,
  #         cipher_suite: :strong,
  #         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
  #         certfile: System.get_env("SOME_APP_SSL_CERT_PATH")
  #       ]
  #
  # The `cipher_suite` is set to `:strong` to support only the
  # latest and more secure SSL ciphers. This means old browsers
  # and clients may not be supported. You can set it to
  # `:compatible` for wider support.
  #
  # `:keyfile` and `:certfile` expect an absolute path to the key
  # and cert in disk or a relative path inside priv, for example
  # "priv/ssl/server.key". For all supported SSL configuration
  # options, see https://plug.hexdocs.pm/Plug.SSL.html#configure/1
  #
  # We also recommend setting `force_ssl` in your config/prod.exs,
  # ensuring no data is ever sent via http, always redirecting to https:
  #
  #     config :harness, HarnessWeb.Endpoint,
  #       force_ssl: [hsts: true]
  #
  # Check `Plug.SSL` for all available options in `force_ssl`.
end
